### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [opencontainers/opencontainers.org#120]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by jdolitsky** [comment]
cc @amye - can you help w/ this?

**Comment by jdolitsky** [comment]
From that link:
> How do I update my build image?
You can upgrade to the latest build image in the Netlify UI under Site settings > Build & deploy > Continuous Deployment > Build image selection.

**Comment by amye** [comment]
@nate-double-u  - what should the build image be

**Comment by nate-double-u** [comment]
I think the new default is Ubuntu 20.04, and should be fine for most cases

**Comment by amye** [comment]
Done!
